/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hfm.gui.panels;

import java.util.ArrayList;
import javax.swing.JRadioButton;
import hfm.controller.HostFileManager;
import hfm.gui.entity.ExpressionContainer;
import hfm.gui.entity.SpecialRadioButton;
import hfm.manager.GUIManager;

/**
 *
 * @author ismailakpolat
 */
public class IpRemovePanel extends javax.swing.JPanel {

    private ArrayList<JRadioButton> radioList;
    private ExpressionContainer container;
            
    public IpRemovePanel(final ExpressionContainer container) {
        initComponents();
        this.container = container;
        int height = 30;
        int width = 150;
        this.setBounds(0, 0, width+50, (container.getIpSize()+1)*height);
        this.setPreferredSize(getSize()); //For option panes to work.
        radioList = new ArrayList<JRadioButton>();
        for(int i=0; i<container.getIpSize(); i++) {
            if(!container.getIpList().get(i).equals("canlı")) {
                final SpecialRadioButton radio = new SpecialRadioButton(i);
                radio.setText(container.getIpList().get(i));
                radio.setBounds(5, i*(height+10), width, height);

                radioList.add(radio);
                add(radio);
            }
        }
    }
    
    /**
     * Removes selected items from..
     */
    public void removeSelecteds() {
        for(int i=0; i < HostFileManager.expressions.size(); i++) {
            //Find corresponding container.
            if(HostFileManager.expressions.get(i).getDnsName().equals(container.getDns())) {
                for(int j=radioList.size()-1; j >=0; j--) {
                    if(radioList.get(j).isSelected()) {
                        HostFileManager.expressions.get(i).removeIp(j);
                        container.removeIp(j);
                    }
                }
            }
        }
        
        GUIManager.instance().updateExpressionsPanel();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
