/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hfm.gui.panels;

import hfm.util.FormattedIpField;

/**
 *
 * @author ismailakpolat
 */
public class IpTextFieldPanel extends javax.swing.JPanel {

    /**
     * Creates new form IpTextFieldPanel
     */
    public IpTextFieldPanel() {
        initComponents();
    }

    public String getIp() {
        return ipField1.getText()+"."+ipField2.getText()+"."+ipField3.getText()+"."+ipField4.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipField1 = new javax.swing.JTextField();
        pointField1 = new javax.swing.JLabel();
        ipField2 = new javax.swing.JTextField();
        ipField3 = new javax.swing.JTextField();
        ipField4 = new javax.swing.JTextField();
        pointField2 = new javax.swing.JLabel();
        pointField3 = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(180, 45));
        setLayout(null);

        ipField1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ipField1.setText("0");
        add(ipField1);
        ipField1.setBounds(6, 6, 38, 28);
        ipField1.setDocument(new FormattedIpField());

        pointField1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pointField1.setText(".");
        add(pointField1);
        pointField1.setBounds(46, 14, 3, 16);

        ipField2.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ipField2.setText("0");
        add(ipField2);
        ipField2.setBounds(50, 6, 38, 28);
        ipField2.setDocument(new FormattedIpField());

        ipField3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ipField3.setText("0");
        add(ipField3);
        ipField3.setBounds(94, 6, 38, 28);
        ipField3.setDocument(new FormattedIpField());

        ipField4.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        ipField4.setText("0");
        add(ipField4);
        ipField4.setBounds(138, 6, 38, 28);
        ipField4.setDocument(new FormattedIpField());

        pointField2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pointField2.setText(".");
        add(pointField2);
        pointField2.setBounds(90, 14, 3, 16);

        pointField3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        pointField3.setText(".");
        add(pointField3);
        pointField3.setBounds(134, 14, 3, 16);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ipField1;
    private javax.swing.JTextField ipField2;
    private javax.swing.JTextField ipField3;
    private javax.swing.JTextField ipField4;
    private javax.swing.JLabel pointField1;
    private javax.swing.JLabel pointField2;
    private javax.swing.JLabel pointField3;
    // End of variables declaration//GEN-END:variables
}
