/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package hfm.gui.panels;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import hfm.config.Config;
import hfm.controller.HostFileManager;
import hfm.entity.Expression;
import hfm.gui.entity.ExpressionContainer;
import hfm.manager.GUIManager;

/**
 *
 * @author ismailakpolat
 */
public final class RightPanel extends javax.swing.JPanel {
    
    private ArrayList<ExpressionContainer> expressContList = new ArrayList<ExpressionContainer>();

    public RightPanel() {
        initComponents();
//        setLocation(780, 0);
//        recreateContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expressionsScroll = new javax.swing.JScrollPane();
        expressionsPanel = new javax.swing.JPanel();
        addDnsButton = new javax.swing.JButton();

        setSize(new java.awt.Dimension(420, 650));
        setLayout(null);

        expressionsScroll.setPreferredSize(new java.awt.Dimension(408, 420));

        expressionsPanel.setPreferredSize(new java.awt.Dimension(408, 900));
        expressionsPanel.setSize(new java.awt.Dimension(408, 900));
        expressionsPanel.setLayout(null);
        expressionsScroll.setViewportView(expressionsPanel);

        add(expressionsScroll);
        expressionsScroll.setBounds(6, 0, 408, 560);

        addDnsButton.setText("Add DNS");
        addDnsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDnsButtonActionPerformed(evt);
            }
        });
        add(addDnsButton);
        addDnsButton.setBounds(310, 560, 97, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void addDnsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDnsButtonActionPerformed
        String dns = JOptionPane.showInputDialog("Dns ismini giriniz.");
        if(dns != null)
            GUIManager.instance().addDnsToExpessions(dns);
    }//GEN-LAST:event_addDnsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDnsButton;
    private javax.swing.JPanel expressionsPanel;
    private javax.swing.JScrollPane expressionsScroll;
    // End of variables declaration//GEN-END:variables

    /**
     * Create content of right panel again.
     */
    public void recreateContent() {
        int i=0;
        if(HostFileManager.expressions != null) {
            expressionsPanel.removeAll();
            expressContList.clear();
            
            HostFileManager.sortExpressions();
            for(Expression expression : HostFileManager.expressions) {
//                System.out.println(expression.getDnsName());
                //Ignore empty lines, start-end spaces. 
    //            if(!expression.trim().equals("")) {
                    expressContList.add(new ExpressionContainer(expression.getDnsName(), expression.getIpList()));
                    expressContList.get(i).setLocations(5, i*50);
                    expressionsPanel.add(expressContList.get(i));
                    i++;
    //            }
            }
        }
        
//        JButton but = new JButton("DNS Tanımla");
//        but.setBounds(expressionsPanel.getWidth()-5-120, i*50, 120, 30);
//        expressionsPanel.add(but);
        expressionsPanel.setPreferredSize(new Dimension(expressionsPanel.getWidth(), expressContList.size()*Config.expressContainerHeight));
        expressionsPanel.setVisible(false);
        expressionsPanel.setVisible(true);
    }
}
